language: node_js
node_js:
  - '10'
os:
- linux
- osx
dist: trusty
osx_image: xcode10
sudo: false

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
  - /^greenkeeper/.*$/

install:
- curl -sSf https://sh.rustup.rs > ./rustup.sh
- chmod +x ./rustup.sh
- ./rustup.sh -y
- source $HOME/.cargo/env
- yarn

script:
- npm run lint
- if test -z "$TRAVIS_TAG"; then travis_wait yarn make; fi
after_success: if test -n "$TRAVIS_TAG"; then yarn publish; fi
